# Generated by Django 5.0.3 on 2024-04-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='product_type',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product_type',
            old_name='Name',
            new_name='name',
        ),
    ]
