# Generated by Django 5.0.2 on 2024-03-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('People_Required', models.PositiveIntegerField()),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Updated_On', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entry', models.TextField()),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Updated_On', models.DateTimeField(auto_now=True)),
                ('Commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='commissions.commission')),
            ],
        ),
    ]
