# Generated by Django 5.0.2 on 2024-05-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='open_manpower',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
