# Generated by Django 5.0.2 on 2024-03-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-Created_On'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['Created_On'], 'verbose_name': 'commission', 'verbose_name_plural': 'commissions'},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('Created_On', 'Entry')},
        ),
    ]
