# Generated by Django 5.0.2 on 2024-05-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-created_on'], 'verbose_name': 'commission', 'verbose_name_plural': 'commissions'},
        ),
    ]
