# Generated by Django 5.0.2 on 2024-04-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_alter_comment_options_alter_commission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_On'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_On'], 'verbose_name': 'commission', 'verbose_name_plural': 'commissions'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Commission',
            new_name='commission',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Created_On',
            new_name='created_On',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Entry',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Updated_On',
            new_name='updated_On',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='Created_On',
            new_name='created_On',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='People_Required',
            new_name='people_Required',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='Updated_On',
            new_name='updated_On',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('created_On', 'entry')},
        ),
    ]
