# Generated by Django 5.0.2 on 2024-04-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_comment_options_alter_commission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on'], 'verbose_name': 'commission', 'verbose_name_plural': 'commissions'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_On',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_On',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='created_On',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='people_Required',
            new_name='people_required',
        ),
        migrations.RenameField(
            model_name='commission',
            old_name='updated_On',
            new_name='updated_on',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('created_on', 'entry')},
        ),
    ]
