# Generated by Django 5.0.2 on 2024-05-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_jobapplication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['role'], 'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
    ]
