# Generated by Django 5.0.2 on 2024-05-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_job_open_manpower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='open_manpower',
            field=models.IntegerField(default=10),
        ),
    ]
