# Generated by Django 4.2.10 on 2024-05-08 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
