# Generated by Django 5.0.2 on 2024-05-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_article_author_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
